export default {
    products:[
        {   _id:'1',
            name:'Slim Shirt',
            categories:'Shirt',
            image:'/images/slim.jpg',
            price:700,
            brand:'Nike',
            rating:3.5,
            numReviews:10,
            countInstock: 6,
        },
        {    _id:'2',
            name:'Baggy pants',
            categories:'Pants',
            image:'/images/slim.jpg',
            price:600,
            brand:'Addidas',
            rating:4.2,
            numReviews:10,
            countInstock: 4,
        },
        
        {    _id:'3',
            name:'Jeans.',
            categories:'Pants',
            image:'/images/slim.jpg',
            price:700,
            brand:'One8',
            rating:4.1,
            numReviews:1000,
            countInstock: 5,
        },
        
        {    _id:'4',
            name:'Culottes ',
            categories:'Pants',
            image:'/images/slim.jpg',
            price:700,
            brand:'Wrogn',
            rating:4.5,
            numReviews:100,
            countInstock: 9
        },
        {    _id:'5',
            name:'Flannel Shirt',
            categories:'Shirt',
            image:'/images/slim.jpg',
            price:900,
            brand:'Nike',
            rating:4.5,
            numReviews:200,
            countInstock: 6,
        },
        {    _id:'6',
            name:'Chambray Shirt',
            categories:'Shirt',
            image:'/images/slim.jpg',
            price:400,
            brand:'Nike',
            rating:4.5,
            numReviews:1000,
            countInstock: 7,
        },
        
        
    ]
}